package entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "logs")
@DynamoDBTable(tableName = "logs")
public class Log {

    @Id
    @JsonIgnore
    @DynamoDBAttribute
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @JsonIgnore
    private long userId;
    @DynamoDBAttribute
    private String key;
    @DynamoDBAttribute
    private String timestamp;
    @DynamoDBAttribute
    private String value;

    public Log(String id, long userId, String key, String timestamp, String value) {
        this.id = id;
        this.timestamp = timestamp;
        this.userId = userId;
        this.key = key;
        this.value = value;
    }

    public Log() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Log log = (Log) o;

        if (userId != log.userId) return false;
        //because we don't know where id getting from
        //if (id != null ? !id.equals(log.id) : log.id != null) return false;
        if (timestamp != null ? !timestamp.equals(log.timestamp) : log.timestamp != null) return false;
        if (key != null ? !key.equals(log.key) : log.key != null) return false;
        return !(value != null ? !value.equals(log.value) : log.value != null);

    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (timestamp != null ? timestamp.hashCode() : 0);
        result = 31 * result + (int) (userId ^ (userId >>> 32));
        result = 31 * result + (key != null ? key.hashCode() : 0);
        result = 31 * result + (value != null ? value.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "Log:  id =" + id + "\ttimestamp =" + timestamp.toString() + "\tuserid =" + userId + "\tkey =" + key + "\tvalue =" + value.toString();
    }
}
